//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyMemberRelation
    {
        public int RelationId { get; set; }
        public string RelationName { get; set; }
        public Nullable<int> FamilyMemberId { get; set; }
        public string ApplicationId { get; set; }
    }
}
