//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Runtime.Remoting.Contexts;

    [Synchronization()]
    public partial class SampleCodeDB : DbContext
    {
        public SampleCodeDB()
            : base("name=SampleCodeDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FamilyMember> FamilyMembers { get; set; }
        public virtual DbSet<FamilyMemberRelation> FamilyMemberRelations { get; set; }
    }
}
